export type UsNewsBlogPost = {
  slug: string
  title: string
  excerpt: string
  body_md: string
  cover_image_url: string | null
  author: string
  tags: string[]
  is_published: boolean
  published_at: string
  source_url: string
}

// Dr. Martin Tibuakuu's U.S. News patient-advice articles.
// Generated by scripts/import-usnews-blog.mjs — re-run to refresh from source.
export const USNEWS_BLOG_POSTS: UsNewsBlogPost[] = [
  {
    slug: 'electronic-cigarettes-are-they-safer-than-traditional-cigarettes',
    title: "Electronic Cigarettes: Are They Safer Than Traditional Cigarettes?",
    excerpt: "Analyzing the evidence.",
    body_md: `Deemed "safer," electronic cigarettes, also known as e-cigarettes or e-cigs, have earned a reputation as an alternative for traditional cigarettes. There's a hot debate about whether traditional cigarette users should switch to e-cigs, which are supposed to be less harmful for your health. But there is little evidence to support the switch.

## What Are E-Cigs?

Unlike traditional cigarettes that deliver nicotine by burning tobacco leaves, e-cigs are battery-operated devices that deliver nicotine with flavorings and other chemicals to users in vapor instead of smoke. They come in different shapes and sizes. Some resemble traditional cigarettes, cigars or pipes, and others resemble everyday items, like pens. There are currently more than 250 different e-cig brands on the market.

In 2014, the Centers for Disease Control and Prevention reported that 12.6 percent of U.S. adults had tried an e-cig, and 3.7 percent regularly used them – including 2.4 million middle and high school students who regularly used in the past 30 days.

## How Do E-Cigs Work?

E-cigs are made of three components:
- A cartridge, which holds a liquid containing varying amounts of nicotine, flavorings and other chemicals
- A heating device that vaporizes the liquid
- A power source (usually a battery)Puffing on an e-cig activates the battery-powered heating device, which vaporizes the liquid in the cartridge into an aerosol that is inhaled – a process popularly known as vaping.

[See: How to Break 7 Unhealthy Habits.]

## Are E-Cigs Safer Than Traditional Cigarettes?

At this time, there isn't sufficient research available to support that e-cigs are safer. Smoking traditional cigarettes remains the leading cause of preventable death and sickness in the U.S., with more than 480,000 people a year dying of smoking-related illnesses. The adverse health effects caused by traditional cigarettes are due to the harmful tar and chemicals they contain. E-cigs are designed to simulate the effect of traditional cigarettes by providing nicotine through an aerosol that feels and looks like tobacco smoke without the harmful tar and other chemicals.

Although e-cig vapor doesn't contain some of the harmful materials found in tobacco smoke, little is known about the health risks of using these devices. Laboratory analyses have shown that the vapor from some e-cigs contains substances that cause cancer and have adverse effects on the heart, blood vessels and lungs. Glycol and propylene are common solvents used in e-cigs that produce many toxic substances when heated and vaporized.

And nanoparticles released into the air from the e-cig's heating mechanism can be toxic to the human body and the environment.It's still unclear whether all e-cigs produce harmful substances. This is because the voltage, temperature, shape, type and age differ from one device to another. Also, the variety of flavors and differences in nicotine levels in e-cigs make it difficult for researchers to come to a firm conclusion about the safety of these devices.

What is known, though, is that e-cig devices tend to produce more harmful products when the voltage is increased and as they age. Most e-cigs contain nicotine. Nicotine is toxic to the nervous system and highly addictive, and it is a well-studied stimulant that increases heart rate and blood pressure. Repeated exposure to nicotine through smoking, vaping or chewing products with nicotine can put people at risk for damaging their heart, lungs, mouth and throat.In addition to nicotine, e-cig aerosols contain carbonyl compounds, such as acrolein, formaldehyde and acetaldehyde, which can cause significant cardiovascular damage and may cause irregular heart rhythm, increased blood clotting and airway irritation.

One concern with the e-cig device is that users can refill the cartridge with a higher, more toxic level of nicotine and increase exposure to potentially hazardous chemicals in the e-cig vapor. The device can also be used to deliver other drugs, as users can refill the cartridge with substances other than nicotine. This can be dangerous for anyone, particularly adolescents and young adults, who are prone to experiment with new products and devices.

## Are E-Cigs Effective for Quitting Smoking?

E-cigs are used as a nicotine replacement therapy for many smokers who want to quit. Nicotine from e-cigs reduces smoking cravings and can help smokers stay away from traditional cigarettes. But recent studies cast doubt on the effectiveness of e-cigs for quitting smoking. They showed that nicotine replacement therapies are only effective when a health care provider prescribes them, not when purchased over the counter.

Also, e-cigs can keep smokers as long-term nicotine users because they have similar pleasurable, addiction-reinforcing properties. As a result, e-cigs could increase the chance of starting smoking again, when compared with other cessation methods. Varenicline and bupropion are approved first-line drugs for quitting smoking that don't contain nicotine and help smokers quit by reducing the urge to smoke. Research has shown the best method for quitting is the combination of Food and Drug Administration-approved smoking cessation products combined with continuous active engagement between individuals and their health care provider.Despite advertising to the contrary, e-cigs impose a considerable risk of secondhand exposure.

Most manufacturers claim that e-cigs produce smokeless water vapor and are therefore harmless. This is inaccurate. E-cigs do not emit pure water vapor. E-cig vapor also contains the same amount of tiny particles found in cigarette smoke that spoil indoor air quality. If inhaled, they can be deposited deep in the lungs and cause respiratory problems not only for the users, but also for anyone secondarily exposed.

[See: The 5 Latest Poison Control Threats Kids Face.]

## What Is the Chance That My Child Will Use E-Cigs?

E-cig use has increased drastically among those under 18. Online marketing, appealing cartridge flavors – such as coffee, cinnamon, mint, fruit and candy – and the fancy looks of these devices have made e-cigarettes very attractive to teenagers and young adults. One study done by the FDA showed that among teens and adults, flavors are the No. 1 reason they use e-cigs. Flavors also boost the rewarding and addictive effects of e-cigs.

The lower cost of e-cigs compared to conventional cigarettes also increases their availability for everyone, including young people.E-cigs familiarize teens with nicotine products and thus could be gateways to traditional cigarette smoking. They may also increase the chance of experimenting with other substances. One study showed that high school students who used e-cigs were more likely to smoke traditional cigarettes within the next year.

In other words, e-cigs have introduced school-aged children to nicotine – children who otherwise wouldn't have used any tobacco products.Some critics argue that frequent public e-cig use among adults familiarizes smoking behavior among children and threatens the stigma associated with smoking in society today. This may neutralize the precious efforts in the last decades that led to the decrease in smoking prevalence.

## It Seems There Are Risks With E-Cig Use. How Are They Regulated?

The FDA now regulates marketing, distribution and advertisement of e-cig products. To protect young people, the FDA banned online and in-person marketing of e-cigs to minors. By the end of 2016, manufacturers will have to report which products they make and how they distribute them. By Feb. 8, 2017, they must clarify the ingredients used in their products. And by June 2018, they need to sell their products with FDA health warning labels – just like any other conventional tobacco products.

[See: 10 Concerns Parents Have About Their Kids' Health.]

## I Was Thinking of Quitting With E-Cigs. What Should I Do Now?

Health professionals highly recommend that you quit smoking to decrease your chances of heart attack, stroke and cancer, and improve your overall health. Consider talking to your doctor about your intentions to quit smoking, and ask about the current approved and effective quitting methods that you could use. If used to quit smoking, e-cigs may not be effective, possibly even augmenting addiction and increasing your dependence on nicotine.

Once again, studies show that smoking cessation therapies are only effective when a doctor has prescribed them, and the FDA has approved effective therapies for quitting smoking. Even though e-cig aerosol contains less harmful substances than cigarette smoke, very limited information is available about the safety of these new devices. The FDA's decision to regulate e-cigs is backed by many scientists and policymakers who believe that concerns about the safety of these products should be addressed.

Once completed, long-term studies on e-cigs use and their health effects will provide more reliable information about their safety.Drs. Kianoush and Tibuakuu are supported by the American Heart Association Tobacco Regulation and Addiction Center (A-TRAC).

---

*Originally published on [U.S. News & World Report](https://health.usnews.com/health-news/patient-advice/articles/2016-09-22/electronic-cigarettes-are-they-safer-than-traditional-cigarettes) by Sina Kianoush, M.D., M.P.H., Martin Tibuakuu, M.D., M.P.H., Erin Michos, M.D., M.H.S.. Republished on PulsePoint Journal for patient education.*`,
    cover_image_url: "https://www.usnews.com/dims4/USNEWS/4db52d7/2147483647/thumbnail/970x647/quality/85/?url=https%3A%2F%2Fwww.usnews.com%2Fcmsmedia%2Ff1%2Fdcf3d3f91a1bab4b4890aed1ebcf52%2F46956WideModern_E-Cigarette_130905.jpg",
    author: "Martin Tibuakuu, MD, MPH, FACC",
    tags: ["patient education","preventive cardiology","smoking-and-tobacco","us-news","vaping"],
    is_published: true,
    published_at: '2016-09-22T12:00:00.000Z',
    source_url: "https://health.usnews.com/health-news/patient-advice/articles/2016-09-22/electronic-cigarettes-are-they-safer-than-traditional-cigarettes",
  },
  {
    slug: 'know-your-a1c-what-this-blood-test-can-tell-you-about-your-risk-for-diabetes-and-cardiovascular-disease',
    title: "Know Your A1C: What This Blood Test Can Tell You About Your Risk for Diabetes and Cardiovascular Disease",
    excerpt: "The higher the A1C level, the greater the risk of developing diabetes-related complications.",
    body_md: `A simple blood test can diagnose diabetes, but it also can tell you so much more, including your risk for heart attack and stroke.

## Type 2 Diabetes: Who Is at Risk?

Diabetes, which causes chronically high blood sugar levels, is the seventh leading cause of death in the United States, according to the Centers for Disease Control and Prevention. It can also result in serious health complications, including heart disease, blindness, kidney failure and lower-extremity amputations. The CDC reports that close to 29.1 million people are currently living with diabetes in America, meaning about 1 of every 11 people has it.

There are different types of diabetes, but Type 2 diabetes accounts for about 90 to 95 percent of all diagnosed diabetes cases.Risk factors for Type 2 diabetes include older age, obesity, a family history of diabetes, prior history of gestational (pregnancy) diabetes, impaired glucose tolerance, physical inactivity and race/ethnicity. African-Americans, Latinos, American Indians and some Asian-Americans and Pacific Islanders are at particularly high risk for Type 2 diabetes.

## What Is Prediabetes?

People with prediabetes have glucose (i.e., blood sugar) levels that do not meet the criteria for diabetes but are too high to be considered normal. These individuals have an increased risk for the development of diabetes and other serious health problems, including heart disease and stroke. According to the CDC, 86 million American adults, or more than 1 of 3 people, have prediabetes. Without lifestyle changes, such as eating healthy foods, getting regular physical activity and maintaining a healthy weight, 15 to 30 percent of these individuals will develop Type 2 diabetes within five years.

[See: Got Diabetes? Why You Must Protect Your Feet.]

## What Is the A1C Blood Test?

The term A1C is short for HbA1c, or hemoglobin A1C. It refers to glycated hemoglobin, which develops when hemoglobin – a protein within red blood cells that carries oxygen – becomes coated with glucose or sugar in the blood. The amount of glucose that combines with this protein is directly proportional to the total amount of sugar in a person's system, and so the higher blood glucose levels are, the higher the A1C level.

Red blood cells have a life span of 120 days; by measuring A1C, clinicians are able to determine average blood sugar levels over approximately two to three months. A1C is particularly important in people with diabetes because the higher the A1C level, the greater the risk of developing diabetes-related complications. After a diabetes diagnosis, A1C is also used for gauging how well treatment controls blood sugar levels.

In the U.S., A1C results are given as a percentage of hemoglobin that is glycated.

## How Does an A1C Test Differ From a Blood Glucose Level?

An A1C measurement is a marker of average blood sugar levels over a period of two to three months, so it is a more stable test assessing longer-term blood sugar control. This means less day-to-day fluctuations to A1C levels due to stress and illness. A1C is often tested using blood samples from the arm, but samples can also be taken from a finger prick. Fasting is not required before A1C testing like it is for the blood glucose test.On the other hand, the blood glucose level gives us the concentration of glucose in the blood only at the time of the test.

Health care providers measure both A1C and blood glucose to ensure good diabetes control, which informs them of the long-term and day-to-day control of blood sugar levels.

## How Do We Diagnose Diabetes and Prediabetes?

Both diabetes and prediabetes may be diagnosed based on either A1C or blood glucose criteria. Blood glucose criteria could either be a blood glucose level measured after an overnight fast or a two-hour blood glucose value after eating 75 grams of sugar.An international committee of experts from the American Diabetes Association, the European Association for the Study of Diabetes and the International Diabetes Federation recommends that the A1C test be the primary test used to diagnose prediabetes and Type 2 diabetes.

## What Are the A1C Criteria for Diabetes and Prediabetes Diagnosis?

A1C can indicate if people have prediabetes or diabetes based on the following: | A1C | Percentage |
| --- | --- |
| Normal | Below 5.7% |
| Prediabetes | 5.7%–6.4% |
| Diabetes | 6.5% or greater |   An A1C level of 6.5 percent or more measured on two separate occasions indicates you have diabetes.If your A1C test returns a reading of 5.7 to 6.4 percent, this indicates you have prediabetes and are at an increased risk of Type 2 diabetes.

At this point, you need to talk to your doctor about appropriate lifestyle changes that could reduce your risk of developing full-blown Type 2 diabetes in the future.It is important to note that normal ranges for A1C levels may vary from one lab to another, so patients who may wish to interpret their own A1C results need to keep this in mind, especially when using a lab that is different from the one used for previous testing.

## What Is the Target A1C Level?

For most people with previous diagnoses of diabetes, a target A1C level of 7 percent or less is a common treatment target. However, this is a general target, and health care teams do tailor targets to meet individual goals. A1C values are not indicators of specific diabetes complications, meaning any complications could arise with any A1C value. However, the closer someone's value is to the normal A1C range, the better.

A person's recommended A1C target should take into account his or her ability to achieve the target without any risk of serious health complications caused by blood sugar levels that are too low (called hypoglycemia).

[See: The Best Diets to Prevent – and Manage – Diabetes.]

## What Are the Benefits of Lowering A1C?

Studies have shown that reducing A1C by 1 percent in people with diabetes reduces the risk of serious health complications involving small vessels of the eyes and kidneys, as well as nerves by almost 25 percent.Also, a study published in the journal BMJ revealed that people with Type 2 diabetes who reduce their A1C level by 1 percent are: 19 percent less likely to suffer cataracts16 percent less likely to suffer heart failure43 percent less likely to suffer amputation or death due to blood vessel diseasesA lower A1C level in the blood means a lower amount of sugar in the blood on average, which reduces the risk of developing complications caused by high blood sugar levels.

## Who Should Get an A1C Test?

Everyone with Type 2 diabetes should be offered an A1C test at least once a year.Some may require an A1C test more often. This is especially true for patients who had a recent change in medication(s) or if a health care team wishes to more frequently monitor a patient's diabetes status to get it under control.For those without diabetes, experts recommend that anyone 45 or older should consider getting tested for A1C, especially if they are overweight.

If they are younger than 45 but are overweight and have one or more additional risk factors for diabetes, they should consider getting tested.

## What Are the Limitations to A1C Testing for Diabetes?

While A1C tests are usually reliable and widely used, it's important to acknowledge that the test may not be accurate in people who:
-  Have insufficient hemoglobin due excessive bleeding (may have a falsely low A1C reading).
-  Have iron-deficiency anemia (may have a falsely high A1C test).
-  Have hemoglobin genetic variations or uncommon forms of hemoglobin, commonly found in African-Americans and people of Mediterranean or Southeast Asian heritage.
-  Have had a recent blood transfusion or have other forms of hemolytic anemia (may have falsely low A1C results)
-  Are pregnant.

[See: How to Cope With Gestational Diabetes.]

## What Can You Do to Protect Yourself From Diabetes?

Anyone can benefit from a reduction of long-term diabetes complications, such as heart attack, stroke, kidney failure and diabetic nerve pain, by controlling their A1C levels through adopting healthy lifestyle practices. The benefit of reducing A1C should not be underestimated. To reduce A1C levels, you can:Eat healthy. By keeping your post-meal blood glucose low, A1C can gradually be reduced in patients with diabetes and prediabetes.

Those with diabetes and prediabetes need to eat foods that are high in nutrition and avoid excess calories. A healthy diet is rich in fruits, vegetables, fiber, lean protein and "good" monounsaturated and polyunsaturated fats in moderation. Saturated fats, refined "simple" carbohydrates and processed foods should be limited. For instance, switching white bread and white rice for whole-grain and brown rice will help reduce blood glucose spikes after a meal.

Understanding what to eat and what to avoid can be challenging. Talk to a registered dietitian if you need help with food choices and meal planning. Tracking daily food intake using a diet diary or calorie-counter app can help keep things in check. Be physically active. By keeping physically active, blood glucose is moved from the blood into cells to produce energy for the body, which lowers blood glucose levels. Also, physical activity improves our body's sensitivity to insulin, a hormone needed to transport glucose into cells.

This means that less insulin is needed to transport large amounts of glucose. Everyone should incorporate physical activity into their daily routine. For those without diabetes, being physically active will help to prevent the onset of prediabetes and Type 2 diabetes. For those with diabetes, it will help them maintain good blood sugar levels. The American Diabetes Association recommends aiming for 30 minutes of moderate- to vigorous-intensity aerobic exercise at least five days a week, or a total of 150 minutes per week.

Moderate intensity means that you are working hard enough that you can talk but not sing during the activity, while vigorous intensity means you can't say more than a few words without pausing for a breath during the activity. Maintain a healthy weight. Losing weight through diet and exercise if you are overweight will significantly improve blood sugar levels, meaning a good A1C measurement.Monitor your numbers. Carefully monitor both blood sugar and A1C levels if you have diabetes.

Your medical team will most likely recommend regular A1C testing to monitor your overall diabetes control over a period of two to three months. However, A1C should never replace blood sugar level monitoring. For instance, people on insulin and other medications that cause hypoglycemia need regular blood glucose monitoring to ensure blood glucose doesn't get too low.

---

*Originally published on [U.S. News & World Report](https://health.usnews.com/health-news/patient-advice/articles/2016-08-24/know-your-a1c-what-this-blood-test-can-tell-you-about-your-risk-for-diabetes-and-cardiovascular-disease) by Martin Tibuakuu, M.D., M.P.H., Erin Michos, M.D., M.H.S.. Republished on PulsePoint Journal for patient education.*`,
    cover_image_url: "https://www.usnews.com/dims4/USNEWS/a9527e8/2147483647/crop/6271x4183+0+0/resize/970x647/quality/85/?url=https%3A%2F%2Fwww.usnews.com%2Fcmsmedia%2Fb0%2F8b%2Fc30698844c2e84a11532868f3d4e%2F160627-bloodtest-editorial.jpg",
    author: "Martin Tibuakuu, MD, MPH, FACC",
    tags: ["diabetes","heart-disease","heart-health","patient education","prediabetes","preventive cardiology","us-news"],
    is_published: true,
    published_at: '2016-08-24T12:00:00.000Z',
    source_url: "https://health.usnews.com/health-news/patient-advice/articles/2016-08-24/know-your-a1c-what-this-blood-test-can-tell-you-about-your-risk-for-diabetes-and-cardiovascular-disease",
  },
]
