-- ============================================================================
-- PulsePoint Clinic - SEO Engine Schema Additions
-- Adds tracking tables for the autonomous SEO content engine
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: seo_engine_drafts
-- Tracks article drafts generated by the autonomous SEO engine
-- Links to blog_posts when published
-- ----------------------------------------------------------------------------
create table public.seo_engine_drafts (
  id uuid primary key default uuid_generate_v4(),
  topic_id text not null,                    -- Engine topic identifier
  target_keyword text not null,
  secondary_keywords text[],
  pillar text not null,
  geo_target text not null default 'columbia',
  patient_persona text not null default 'general',
  content_angle text,

  -- Draft content
  slug text unique not null,
  title text not null,
  excerpt text,
  body_md text not null,
  meta_title text,
  meta_description text,
  cover_image_prompt text,

  -- Quality metrics
  readability_score numeric(5,2),
  word_count integer,
  keyword_density jsonb,
  quality_score integer,                     -- 0-100 composite score
  quality_checks jsonb,                      -- Full quality report

  -- Physician review workflow
  status text not null default 'draft'
    check (status in ('draft', 'physician-review', 'approved', 'rejected', 'published', 'archived')),
  physician_notes text,
  reviewed_by text,
  reviewed_at timestamptz,

  -- Publishing
  published_slug text references public.blog_posts(slug) on delete set null,
  published_at timestamptz,

  -- Performance tracking
  impressions integer default 0,
  clicks integer default 0,
  ctr numeric(5,2) default 0,
  average_position numeric(5,1),
  last_synced_at timestamptz,

  -- Audit
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index seo_engine_drafts_status_idx
  on public.seo_engine_drafts (status, created_at desc);
create index seo_engine_drafts_keyword_idx
  on public.seo_engine_drafts (target_keyword);
create index seo_engine_drafts_pillar_idx
  on public.seo_engine_drafts (pillar, created_at desc);

create trigger seo_engine_drafts_set_updated_at
  before update on public.seo_engine_drafts
  for each row execute function public.set_updated_at();

-- RLS: Only authenticated admins can access
alter table public.seo_engine_drafts enable row level security;

create policy "Authenticated admins can manage SEO drafts"
  on public.seo_engine_drafts
  for all
  to authenticated
  using (true)
  with check (true);

-- ----------------------------------------------------------------------------
-- TABLE: seo_engine_topics_queue
-- Future article topics queued by the engine
-- ----------------------------------------------------------------------------
create table public.seo_engine_topics_queue (
  id uuid primary key default uuid_generate_v4(),
  topic_id text unique not null,
  pillar text not null,
  title text not null,
  target_keyword text not null,
  secondary_keywords text[],
  semantic_entities text[],
  geo_target text not null default 'columbia',
  patient_persona text not null default 'general',
  intent text not null default 'informational',
  content_angle text,
  opportunity_score integer not null default 50, -- 0-100
  source text not null default 'autonomous-engine',
  seasonality text,                                -- e.g., 'heart-month'

  -- Scheduling
  scheduled_date date,
  assigned boolean default false,
  draft_id uuid references public.seo_engine_drafts(id) on delete set null,

  -- Status
  status text not null default 'queued'
    check (status in ('queued', 'assigned', 'drafting', 'review', 'approved', 'published', 'archived')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index seo_engine_topics_queue_status_idx
  on public.seo_engine_topics_queue (status, opportunity_score desc);
create index seo_engine_topics_queue_scheduled_idx
  on public.seo_engine_topics_queue (scheduled_date, assigned);

create trigger seo_engine_topics_queue_set_updated_at
  before update on public.seo_engine_topics_queue
  for each row execute function public.set_updated_at();

alter table public.seo_engine_topics_queue enable row level security;

create policy "Authenticated admins can manage topic queue"
  on public.seo_engine_topics_queue
  for all
  to authenticated
  using (true)
  with check (true);

-- ----------------------------------------------------------------------------
-- TABLE: seo_engine_performance_log
-- Monthly snapshot of article performance metrics
-- ----------------------------------------------------------------------------
create table public.seo_engine_performance_log (
  id uuid primary key default uuid_generate_v4(),
  draft_id uuid references public.seo_engine_drafts(id) on delete cascade,
  slug text not null,
  month text not null,                          -- 'YYYY-MM'
  impressions integer default 0,
  clicks integer default 0,
  ctr numeric(5,2) default 0,
  average_position numeric(5,1),
  time_on_page integer,                          -- seconds
  bounce_rate numeric(5,2),
  conversions integer default 0,
  indexed boolean default true,

  created_at timestamptz not null default now()
);

create index seo_engine_performance_log_draft_month_idx
  on public.seo_engine_performance_log (draft_id, month);

create trigger seo_engine_performance_log_set_updated_at
  before update on public.seo_engine_performance_log
  for each row execute function public.set_updated_at();

alter table public.seo_engine_performance_log enable row level security;

create policy "Authenticated admins can manage performance logs"
  on public.seo_engine_performance_log
  for all
  to authenticated
  using (true)
  with check (true);

-- ----------------------------------------------------------------------------
-- VIEW: seo_engine_dashboard
-- Combined view for the physician review dashboard
-- ----------------------------------------------------------------------------
create or replace view public.seo_engine_dashboard as
select
  d.id,
  d.topic_id,
  d.status,
  d.pillar,
  d.title,
  d.target_keyword,
  d.geo_target,
  d.word_count,
  d.quality_score,
  d.readability_score,
  d.physician_notes,
  d.reviewed_by,
  d.reviewed_at,
  d.published_at,
  d.created_at,
  coalesce(p.impressions, 0) as last_impressions,
  coalesce(p.clicks, 0) as last_clicks,
  coalesce(p.ctr, 0) as last_ctr,
  coalesce(p.average_position, 0) as last_position
from public.seo_engine_drafts d
left join lateral (
  select * from public.seo_engine_performance_log
  where draft_id = d.id
  order by month desc
  limit 1
) p on true
order by d.created_at desc;

-- RLS for view (inherits from underlying tables but add explicit)
create policy "Authenticated admins can view dashboard"
  on public.seo_engine_dashboard
  for select
  to authenticated
  using (true);
